### ISSUE TITLE
Can't assign prefs

### ISSUE THREAD

**Issue by fiee** [Narsil/django-userpreferences#1]
If I try the same like in your README...

```
        prefs = user.preferences.get('base')
        prefs['send_newsletter'] = form.cleaned_data['send_newsletter']
        user.preferences['base'] = prefs # ERROR
        user.preferences.save()
        user.save()
```

... I get "UserPreferences object does not support item assignment".
Do you have a clue why?

My preferences.py is at base.preferences.

**Comment by Narsil** [comment]
Hi, 

There is indeed a mistake in the README, which should be corrected now.
It is because in order to save you need to use:

```
user.preferences.preferences['base'] = prefs
user.preferences.save()
```

This use is rather unintuitive I must admit. Do you think having something like

```
prefs = user.preferences.get('base')
## Update prefs
user.preferences.set('base', prefs)
```

as a wrapper be more coherent ?

I would rather not even use get and set, and use preferences just a regular dict. I'm just no sure about to do it correctly.

**Comment by fiee** [comment]
Sorry, I missed that double "preferences".
Since there is "get", "set" would be rather logical IMHO.
Perhaps as

```
user.preferences.set('base/foo', 'bar')
```

Of course it would be most pythonic if one could use user.preferences like an ordinary dict, e.g.

```
user.preferences['base']['foo'] = 'bar'
```
